# Generated by Django 5.2.2 on 2025-06-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='ocuppation',
            field=models.CharField(choices=[('profesor', 'Teacher'), ('administrativo', 'Administrative')], default='administrativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anon', max_length=100),
        ),
    ]
