# Generated by Django 5.2.2 on 2025-06-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ocuppation',
        ),
    ]
