# Generated by Django 5.2.2 on 2025-06-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_ocuppation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email_user_idx'),
        ),
    ]
