# Generated by Django 5.2.2 on 2025-06-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='type_number',
            field=models.IntegerField(choices=[(0, 'Preschool'), (1, 'Primary'), (2, 'High')], default=0),
        ),
    ]
