# Generated by Django 5.2.2 on 2025-06-20 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_grade_type_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='El titulo de la foto es muy corto')]),
        ),
    ]
