# Generated by Django 5.2.2 on 2025-06-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_paymentinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
