# Generated by Django 5.2.2 on 2025-08-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_paymentinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingformat',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='school.school'),
        ),
        migrations.AlterModelTable(
            name='settingformat',
            table='setting_format',
        ),
    ]
