# Generated by Django 5.2.2 on 2025-08-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_settingformat_school_alter_settingformat_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewMedia',
            new_name='NewsMedia',
        ),
    ]
