# Generated by Django 5.2.2 on 2025-08-30 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_newmedia_newsmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturaleventmedia',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo de la foto es muy corto')]),
        ),
        migrations.AlterField(
            model_name='download',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo del archivo es muy corto')]),
        ),
        migrations.AlterField(
            model_name='extraactivitiefile',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo del archivo es muy corto')]),
        ),
        migrations.AlterField(
            model_name='extraactivitiephoto',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo de la foto es muy corto')]),
        ),
        migrations.AlterField(
            model_name='infraestructuremedia',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo de la foto es muy corto')]),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo de la foto es muy corto')]),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo de la foto es muy corto')]),
        ),
        migrations.AlterField(
            model_name='repositorymediafile',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=100, message='El titulo del archivo es muy corto')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='La información de la dirección es muy corta')]),
        ),
    ]
