# Generated by Django 5.2.2 on 2025-08-30 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_culturaleventmedia_title_alter_download_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='section',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='El nombre es muy corto')]),
        ),
    ]
