# Generated by Django 5.2.2 on 2025-08-30 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_culturaleventmedia_title_alter_download_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraactivitieschedule',
            name='type',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='La descripción del horario de la actividad, es muy corta')]),
        ),
    ]
