# Generated by Django 5.2.2 on 2025-09-16 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_extraactivitieschedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timegroup',
            name='type',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='La descripción sobre el tipo de grupo horario, es muy corta')]),
        ),
    ]
