# Generated by Django 5.2.2 on 2025-09-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_timegroup_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraactivitie',
            name='files',
        ),
        migrations.RemoveField(
            model_name='extraactivitie',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='extraactivitie',
            name='schedules',
        ),
        migrations.RemoveField(
            model_name='extraactivitie',
            name='school',
        ),
        migrations.RemoveField(
            model_name='extraactivitieschedule',
            name='daysweek',
        ),
        migrations.DeleteModel(
            name='ExtraActivitieFile',
        ),
        migrations.DeleteModel(
            name='ExtraActivitiePhoto',
        ),
        migrations.DeleteModel(
            name='ExtraActivitie',
        ),
        migrations.DeleteModel(
            name='ExtraActivitieSchedule',
        ),
    ]
