# Generated by Django 5.2.2 on 2025-09-26 00:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_extraactivitie_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='El titulo del archivo es muy corto')])),
                ('file', models.URLField()),
            ],
            options={
                'verbose_name': 'Archivo de actividad extracurricular',
                'verbose_name_plural': 'Archivos de actividades extracurriculares',
                'db_table': 'extra_activity_file',
            },
        ),
        migrations.CreateModel(
            name='ExtraActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='El titulo de la foto es muy corto')])),
                ('photo', models.URLField()),
            ],
            options={
                'verbose_name': 'Foto de actividad extracurricular',
                'verbose_name_plural': 'Fotos de actividades extracurriculares',
                'db_table': 'extra_activity_photo',
            },
        ),
        migrations.CreateModel(
            name='ExtraActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='La descripción del horario de la actividad, es muy corta')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('daysweek', models.ManyToManyField(to='school.daysweek')),
            ],
            options={
                'verbose_name': 'Horario de actividade extracurricular',
                'verbose_name_plural': 'Horarios de actividades extracurriculares',
                'db_table': 'extra_activity_schedule',
            },
        ),
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='El titulo de la actividad es muy corto')])),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitiesList', to='school.school')),
                ('photos', models.ManyToManyField(to='school.extraactivityfile')),
                ('files', models.ManyToManyField(to='school.extraactivityphoto')),
                ('schedules', models.ManyToManyField(to='school.extraactivityschedule')),
            ],
            options={
                'verbose_name': 'Actividad extracurricular',
                'verbose_name_plural': 'Actividades extracurriculares',
                'db_table': 'extra_activity',
                'ordering': ['-created', '-updated'],
                'indexes': [models.Index(fields=['school'], name='extra_activity_school_idx'), models.Index(fields=['created'], name='extra_activity_created_idx')],
            },
        ),
    ]
