# Generated by Django 5.2.2 on 2025-10-02 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_extraactivityfile_extraactivityphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preescolar', 'Preschool'), ('básica', 'Primary'), ('secundaria', 'High')], default='básica', max_length=11)),
                ('type_number', models.PositiveSmallIntegerField(choices=[(1, 'Preschool'), (2, 'Primary'), (3, 'High')], default=2, editable=False)),
            ],
            options={
                'verbose_name': 'Etapa educativa',
                'verbose_name_plural': 'Etapas educativas',
                'db_table': 'educational_stage',
                'ordering': ['type_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['stage__type_number', 'level'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados de la escuela'},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='type',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='type_number',
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='El nivel elegido es muy alto'), django.core.validators.MinLengthValidator(limit_value=1, message='El nivel elegido es muy bajo')]),
        ),
        migrations.AddField(
            model_name='grade',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagesList', to='school.educationalstage'),
        ),
    ]
