# Generated by Django 5.2.2 on 2025-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_educationalstage_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraactivity',
            name='files',
            field=models.ManyToManyField(to='school.extraactivityfile'),
        ),
        migrations.AlterField(
            model_name='extraactivity',
            name='photos',
            field=models.ManyToManyField(to='school.extraactivityphoto'),
        ),
    ]
