# Generated by Django 5.2.2 on 2025-11-26 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_extraactivity_files_alter_extraactivity_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=10, message='El nivel elegido es muy alto'), django.core.validators.MinValueValidator(limit_value=1, message='El nivel elegido es muy bajo')]),
        ),
    ]
