# Generated by Django 5.2.2 on 2025-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='section',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
