# Generated by Django 5.2.2 on 2025-12-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_grade_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalstage',
            name='type',
            field=models.CharField(choices=[('preescolar', 'Preschool'), ('básica', 'Primary'), ('secundaria', 'High')], default='básica', editable=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='educationalstage',
            name='type_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Preschool'), (2, 'Primary'), (3, 'High')], default=2, unique=True),
        ),
    ]
