# Generated by Django 5.2.2 on 2026-05-17 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_educationalstage_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='download',
            name='download_title_idx',
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='download',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='El nombre del archivo es muy corto')]),
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('name', 'school')},
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['name'], name='download_name_idx'),
        ),
    ]
