# Generated by Django 5.2.2 on 2026-05-17 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_download_download_title_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='El nombre del archivo es muy corto')]),
        ),
    ]
