# Generated by Django 5.2.2 on 2026-06-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_download_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='culturalevent',
            unique_together={('title', 'date', 'school')},
        ),
    ]
