# Generated by Django 5.2.2 on 2026-07-27 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_culturalevent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='El titulo de la foto es muy corto')])),
                ('photo', models.URLField()),
            ],
            options={
                'verbose_name': 'Foto de recibo de pago',
                'verbose_name_plural': 'Fotos sobre los recibos de pago',
            },
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='title',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='media',
            field=models.ManyToManyField(to='school.paymentinfomedia'),
        ),
    ]
